name: cyber_secu_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  pointycastle: ^2.0.0
  asn1lib: ^0.8.1
  shared_preferences: ^0.5.12+4
  downloads_path_provider_28: ^0.1.0
  open_file: ^3.0.1
  permission_handler: ^4.0.0
  path_provider: ^1.6.5
  file_picker: ^2.0.13
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
